version: '3.8'

services:
  sitemap-generator:
    build: .
    environment:
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
    volumes:
      - ./sitemaps:/app/sitemaps
